#!/usr/bin/env python3
"""Enumerate CDS C-positions in the SAME ORDER as the Vienna cache under
`experiments/multi_enzyme/outputs/exome_map/vienna_cache/chr{N}_vienna.json.gz`.

Why we need this:
    The existing Vienna cache was generated by `exp_exome_editability_full.py`
    using `parse_refgene_exons()` which keeps the longest TRANSCRIPT per gene.
    The newer `scripts/gcp_panel/enumerate_candidates.py` keeps the longest
    CDS per gene. These produce different candidate sets
    (chr22: 200,728 in cache vs 206,816 in candidates_CDS.parquet).

    To reuse the cached 8.5 M MFE structures (7.5 GB of prior compute) without
    refolding, downstream RNA-FM + scoring must iterate candidates in the
    cache's order. This script re-runs the cache's exact enumeration and
    emits `candidates_cache_aligned.parquet` with one row per cache entry.

Verification:
    For each chromosome, the number of rows must equal the cache's
    `n_positions`, and the 201-nt window extracted at each row's
    (chrom, pos, strand) must have a 'C' at index 100.

Output:
    data/processed/gcp_panel/candidates_cache_aligned.parquet
        columns: chrom, pos, strand, gene
    data/processed/gcp_panel/candidates_cache_aligned_summary.json
"""
from __future__ import annotations

import gzip
import json
import logging
import sys
import time
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
from pyfaidx import Fasta

sys.stdout.reconfigure(line_buffering=True)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
HG19_FA = PROJECT_ROOT / "data" / "raw" / "genomes" / "hg19.fa"
REFGENE_HG19 = PROJECT_ROOT / "data" / "raw" / "genomes" / "refGene_hg19.txt"
VIENNA_CACHE_DIR = (PROJECT_ROOT / "experiments" / "multi_enzyme" / "outputs" /
                    "exome_map" / "vienna_cache")
OUT_DIR = PROJECT_ROOT / "data" / "processed" / "gcp_panel"
OUT_DIR.mkdir(parents=True, exist_ok=True)

ALL_CHROMS = [f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"]


def parse_refgene_exons():
    """Duplicate of exp_exome_editability_full.py::parse_refgene_exons (longest TRANSCRIPT per gene)."""
    cols = ["bin", "name", "chrom", "strand", "txStart", "txEnd",
            "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds",
            "score", "name2", "cdsStartStat", "cdsEndStat", "exonFrames"]
    df = pd.read_csv(REFGENE_HG19, sep="\t", header=None, names=cols, low_memory=False)
    df = df[df["chrom"].isin(set(ALL_CHROMS))]
    df = df[df["cdsStart"] != df["cdsEnd"]]
    df["tx_len"] = df["txEnd"] - df["txStart"]
    df = df.sort_values("tx_len", ascending=False).drop_duplicates(subset="name2", keep="first")
    exons_by_chrom = defaultdict(list)
    for _, row in df.iterrows():
        chrom = row["chrom"]; strand = row["strand"]; gene = row["name2"]
        cds_start = row["cdsStart"]; cds_end = row["cdsEnd"]
        starts = [int(x) for x in row["exonStarts"].rstrip(",").split(",")]
        ends = [int(x) for x in row["exonEnds"].rstrip(",").split(",")]
        for es, ee in zip(starts, ends):
            cs = max(es, cds_start); ce = min(ee, cds_end)
            if cs < ce:
                exons_by_chrom[chrom].append((cs, ce, strand, gene))
    return exons_by_chrom


def enumerate_chrom(chrom: str, exons: list, genome: Fasta) -> pd.DataFrame:
    """Duplicate of exp_exome_editability_full.py::process_chromosome's position loop."""
    chrom_len = len(genome[chrom])
    chrom_seq = str(genome[chrom])
    positions = []  # (pos, strand, gene)
    for exon_start, exon_end, strand, gene in exons:
        for pos in range(exon_start, exon_end):
            base = chrom_seq[pos].upper()
            if strand == "+" and base == "C":
                if pos >= 100 and pos + 101 <= chrom_len:
                    positions.append((pos, "+", gene))
            elif strand == "-" and base == "G":
                if pos >= 100 and pos + 101 <= chrom_len:
                    positions.append((pos, "-", gene))
    return pd.DataFrame(positions, columns=["pos", "strand", "gene"])


def main():
    logger.info("Loading hg19 genome from %s", HG19_FA)
    genome = Fasta(str(HG19_FA))

    logger.info("Parsing refGene (longest TRANSCRIPT per gene — cache-compatible)")
    exons_by_chrom = parse_refgene_exons()

    all_rows = []
    summary = {"per_chrom": {}}
    for chrom in ALL_CHROMS:
        exons = exons_by_chrom.get(chrom, [])
        df_chr = enumerate_chrom(chrom, exons, genome)
        df_chr.insert(0, "chrom", chrom)

        cache_path = VIENNA_CACHE_DIR / f"{chrom}_vienna.json.gz"
        cache_n = None
        if cache_path.exists():
            # Only read the small prefix: n_positions is in top-level JSON
            with gzip.open(cache_path, "rt") as f:
                # Cheap peek: load just the first few bytes up to "n_positions"
                # Safer to load the whole JSON — it's a few hundred MB per chrom
                # but we need it for alignment anyway. Keep simple.
                head = json.load(f)
                cache_n = head.get("n_positions", None)

        match = (cache_n == len(df_chr))
        summary["per_chrom"][chrom] = {
            "n_enumerated": len(df_chr),
            "n_cache": cache_n,
            "aligned": bool(match),
        }
        all_rows.append(df_chr)
        flag = "OK" if match else f"MISMATCH (cache={cache_n})"
        logger.info("  %s: %d positions  %s", chrom, len(df_chr), flag)

    df_all = pd.concat(all_rows, ignore_index=True)
    n_all = len(df_all)
    summary["total"] = n_all
    summary["all_aligned"] = all(r["aligned"] for r in summary["per_chrom"].values())

    out_parquet = OUT_DIR / "candidates_cache_aligned.parquet"
    df_all.to_parquet(out_parquet, index=False)
    with open(OUT_DIR / "candidates_cache_aligned_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    logger.info("TOTAL: %d positions across %d chromosomes (%s parquet MB)",
                n_all, len(ALL_CHROMS), f"{out_parquet.stat().st_size/1e6:.1f}")
    logger.info("All chromosomes aligned to cache: %s", summary["all_aligned"])
    logger.info("Wrote %s", out_parquet)


if __name__ == "__main__":
    main()
